version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres"
    container_name: "postgres"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "postgres"
    volumes:
       - ./dump:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
